name: docker-publish

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

env: 
  IMAGE_TAG_SLUG: hls4ml-0.7.1-tutorial
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        ref: 'main'
      - 
        name: "Set environmental variables"
        run: |
          echo "IMAGE_TAG=$REGISTRY/$REPO_NAME/$IMAGE_TAG_SLUG" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push - stock image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: docker/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_TAG }}:latest
            ${{ env.IMAGE_TAG }}:${{ env.COMMIT_SHA }}
      - 
        name: "Update Binder shim Dockerfile"
        run: |
          source ./binder/write_binder_dockerfile.sh
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add ./binder/*
          git commit -m "Updating Binder Dockerfile for commit: $COMMIT_SHA [skip actions]"
          git push
